### PR TITLE
Improve OptimizePointingFOV util using parallel jobs

### PR DESCRIPTION
**Pull request by adalava**
This patch makes it use all available CPU by default when computing the best FOV overlap. The number of parallel jobs can be configured using parameter "parallel_jobs".

Tested using "time python -m wmpl.Utils.OptimizePointingsFOV" command on "Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz", where computing time reduced from 15m25s to 3m29s. This is a single socket, 4 cores with 2 threads per socket, allowing the script to run 8 jobs at once.

### CODE REVIEW

**Comment by markmac99** [comment]
Apart from that, it looks good! I don't use this functionality much as we have almost too many cameras in the UK (hence no optimal pointing direction for any new one!) but i know it is very useful and a performance boost would be good.

**Comment by markmac99** [comment]
I saw the quick update - thanks ! All good from me.

**Comment by adalava** [comment]
> You'll need to update the README to add joblib to the conda install instructions for people using conda.

Certainly! Patch updated, thanks!

**Comment by dvida** [comment]
This is a great addition, thanks! We actually already have identical functionality that joblib has in wmpl, see wmpl.Utils.PyDomanParallelizer. This will allow us to drop the dependency on the new library and not break any existing installations. Would you mind changing the code? I think the interface is virtually identical and it should be an easy fix. Thanks!

**Comment by adalava** [comment]
> This is a great addition, thanks! We actually already have identical functionality that joblib has in wmpl, see wmpl.Utils.PyDomanParallelizer. This will allow us to drop the dependency on the new library and not break any existing installations. Would you mind changing the code? I think the interface is virtually identical and it should be an easy fix. Thanks!

Sure! It was easy to use PyDomanParallelizer and the time measurements was exactly the same, thanks!

**Pull request merged**
